services:
  back:
    image: flashcii-back:latest
    environment:
      - DATABASE_USERNAME=changeusername
      - DATABASE_PASSWORD=changepassword
      - LOG_LEVEL_ROOT=INFO
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SQL=INFO
      - LOG_LEVEL_SQL_TRACE=INFO
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"
    volumes:
      - "./container-test:/app/data:Z"
