spring:
  application:
    name: flashcii-cli
  datasource:
    url: jdbc:h2:file:./data/flashciicards-db;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Automatically create the schema for H2 during runtime
    show-sql: true # Optional: Enable SQL query logging
  main:
    banner-mode: "off" # Disable banner for CLI for cleaner output
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.clemnjord.flashcii: DEBUG # Detailed logs for the application namespace
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# Custom properties for CLI behavior (if required)
cli:
  output:
    ansi: "always" # Ensure colorful terminal output (if using ANSI coloring)
  prompt:
    default: "flashcii> " # Default command prompt for the CLI