[versions]
aspectj = "1.9.24"
assertj = "3.27.3"
h2 = "2.3.232"
jansi = "2.4.2"
junit = "6.0.1"
lombok = "1.18.38"
mapstruct = "1.6.3"
mockito = "5.17.0"
pitest = "1.19.4"
pitest-junit5 = "1.2.3"
slf4j = "2.0.17"
spring-aspects = "6.2.9"
spring-boot = "3.5.4"
springdoc-openapi = "2.8.9"

# Plugins
spotless-plugin = "8.1.0"
gradle-test-logger-plugin = "4.0.0"

[libraries]
# Database dependencies
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

# Development dependencies
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }

# Logging dependencies
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Spring dependencies
aspectj = { group = "org.aspectj", name = "aspectjweaver", version.ref = "aspectj" }
spring-aspects = { group = "org.springframework", name = "spring-aspects", version.ref = "spring-aspects" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
springdoc-openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }

# Test dependencies
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }

[plugins]
spotless-plugin = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
gradle-test-logger-plugin = { id = "com.adarshr.test-logger", version.ref = "gradle-test-logger-plugin" }
gradle-plugin = { id="org.springframework.boot", version.ref = "spring-boot"}