spring:
  application:
    name: flashcii-web
  main:
    banner-mode: "off" # Disable banner for CLI for cleaner output
  profiles:
    group:
      default: h2-file
      test: h2-mem

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.clemnjord.flashcii: ${LOG_LEVEL_APP:DEBUG} # Detailed logs for the application namespace
    org:
      hibernate:
        SQL: ${LOG_LEVEL_SQL:DEBUG}
        type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_TRACE:TRACE}

server:
  port: ${SERVER_PORT:8083}