spring:
  application:
    name: flashcii-web
  main:
    banner-mode: "off" # Disable banner for CLI for cleaner output
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev:
      - pgsql
      - hibernate-dev
      - dev-log
      test:
      - pgsql
      - hibernate-dev
      - test-log

server:
  port: ${SERVER_PORT:8083}